name: cached_network_image
description: Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
version: 0.6.0-alpha.2
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cached_network_image

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: "^0.3.0-alpha.2"

dev_dependencies:
  test: ^1.3.0