name: cached_network_image
description: Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
version: 2.0.0
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cached_network_image

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.15-pre.148 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: "^1.1.3"

dev_dependencies:
  pedantic: "^1.8.0+1"
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
