name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.2.0
homepage: https://github.com/Baseflow/flutter_cached_network_image

environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface: ^4.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
